### ISSUE TITLE
RSpec Rails 6.0 Release Plan

### ISSUE THREAD

**Issue by JonRowe** [rspec/rspec-rails#2560]
@pirj @benoittgt we need to get some rspec-rails releases out, these are the steps we need to complete to do this:

- [x] Merge / Cherry pick to `5-0-maintenance` any outstanding 6.x patches we can
  - [x] Support for Ruby 3.1 #2564
- [x] Release `5.0.3` 
- [x] Create `5-1-maintenance` without the Rails 7 patches.
- [x] Merge / Cherry pick to `5-1-maintenance` the final few tweaks for rails 6.1.
   - [x]  Support for Ruby 3.1 #2562
- [x] Release `5.1.0`
- [ ] Essential to merge to main
  - [x] Support for Ruby 3.1 #2563
  - [x] #2521
  - [x] #2552 
  - [ ] Sort out the mailer merges
  - [x] #2587
- [x] Optionally
  - [x] Release RSpec libs at 3.11
  - [x] Merge to main #2511 (see 3.11)
  - [x] Merge to main #2508
  - [x] Merge to main #2387
  - [x] Merge #2614
- [x] Merge #2567
- [ ] Release 6.0.0 supporting Rails 7, dropping Rails 5, minimum rspec version 3.11.

This is because major version changes are required for new rails versions for us under our release policy, but this means a bunch of branch wrangling, we could drop some of the changes for main in the name of expediency, thoughts?

**Comment by pirj** [comment]
> we could drop some of the changes for main in the name of expediency

Sounds good.
I've restored the branch for #2546, those who want to have support for Rails 7 right now can use `combo-have_enqueued_mail-fixes` branch meanwhile.

**Comment by JonRowe** [comment]
> I've restored the branch for #2546, those who want to have support for Rails 7 right now can use combo-have_enqueued_mail-fixes branch meanwhile.

Why? It's still merged in `main`. Only the new `5-1-maintenance` skips it?

**Comment by pirj** [comment]
Because I've [suggested using this branch](https://github.com/rspec/rspec-rails/pull/2546#issuecomment-1016238904) :see_no_evil: thinking that this commit will be taken out of `main`.

**Comment by JonRowe** [comment]
Please feel free to merge any rails 7 fixes to `main` as I intend to release this within a reasonable timeframe, if we were developing a longer term stable (like rspec 4) i'd revert but for rspec-rails its just as easy to pull the commits out of the stable 5.x series.

**Comment by pirj** [comment]
I'd prefer merging https://github.com/rspec/rspec-rails/pull/2508 to main after releasing 5.1.x for simplicity.
Edited the description.

**Comment by pirj** [comment]
`5-1-development` is ready for 5.1.0 release, @JonRowe

**Comment by JonRowe** [comment]
I'm afraid its not @pirj, you merged my PR prematurely.

**Comment by JonRowe** [comment]
`5.0.3` and `5.1.0` are released

**Comment by leboshi** [comment]
FYI, #2325 is moot now; 3 commits, the last of them 3ccd1f on 1/20/2022, made it obsolete.

**Comment by JonRowe** [comment]
I've released `6.0.0.rc1` with the changes so far in order to help those who need a release without a git dependency. Theres mostly the mailer behaviour changes to sort out before releasing a final version, and the tagged logging pr.

**Comment by pirj** [comment]
@JonRowe Speaking of sorting out the mailer merges, it appears to me that we didn't introduce any breaking changes, on the contrary, we've fixed a deficiency when with `ActionMailer::MailDeliveryJob`, users had to add `args:`.

Everyone seems happy so far with 6.0.0-rc1, and I have several theories for that:

1. It is not widespread enough with just [80K downloads](https://rubygems.org/gems/rspec-rails/versions/6.0.0.rc1) compared to 2.5M downloads of 5.1.2. A counterargument is that it is specifically used by those early adopters who needed the fix, and the fix worked.

2. There are very, very few usages of mailer matchers [in the wild](https://github.com/pirj/real-world-rspec):
```ruby
$ cd ~/source/real-world-rspec
$ rg --hidden --no-ignore --files-with-matches 'have_enqueued_mail|enqueue_mail|have_enqueued_email|enqueue_email'
rspec-rails/lib/rspec/rails/matchers/have_enqueued_mail.rb
rspec-rails/lib/rspec/rails/matchers.rb
rspec-rails/spec/rspec/rails/matchers/have_enqueued_mail_spec.rb
rspec-rails/Changelog.md
rspec-rails/features/matchers/have_enqueued_mail_matcher.feature
chatwoot/spec/controllers/platform/api/v1/users_controller_spec.rb
gitlabhq/spec/services/users/approve_service_spec.rb
gitlabhq/spec/services/notification_service_spec.rb
gitlabhq/spec/controllers/admin/users_controller_spec.rb
gitlabhq/spec/controllers/registrations_controller_spec.rb
gitlabhq/spec/support/helpers/notification_helpers.rb
gitlabhq/spec/requests/api/users_spec.rb
gitlabhq/spec/models/user_spec.rb
```

3. The fix worked for all combinations of Rails versions and delivery job class.

Basing on this, I suggest considering this item complete.

**Comment by JonRowe** [comment]
I think it makes sense to move on and release `6.0.0` as it is, we can address any resulting breaking changes in `7.0.0`
